### ISSUE TITLE
Execution of jlink failed

### ISSUE THREAD

**Issue by jakweg** [Nithanim/cultures-multitool#4]
Hey
When I try to build the tool I'm getting an Error: automatic module cannot be used with jlink: javafx.fxmlEmpty
Do you know how to fix it?

**Comment by Nithanim** [comment]
Sorry, for your inconvenience! Seems it broke at some point. I have added another way to run this application and updated the [README.md](../blob/master/README.md) accordingly. Since I am not on Windows I can't test it but I hope it works like on Linux.

**Comment by jakweg** [comment]
Thanks, it now works on my Linux machine.

**Comment by Nithanim** [comment]
Glad it works for you now! If you have any further issues, just contact me! :)
